# Включаем ZMK Studio (уже добавили ранее)
CONFIG_ZMK_STUDIO=y

# Включаем поддержку разделения (Split)
CONFIG_ZMK_SPLIT=y

# --- НАСТРОЙКА БАТАРЕИ ---
# Включаем отчетность по батарее для хоста (ПК)
CONFIG_ZMK_BATTERY_REPORTING=y
# Разрешаем донглу запрашивать уровень заряда у клавиатуры
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
# Разрешаем донглу передавать заряд клавиатуры в ОС компьютера
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y