# Переводим клавиатуру в режим беспроводного сателлита (Peripheral)
CONFIG_ZMK_SPLIT=y


# Включаем режим сна для экономии батарейки на самой клаве (например, через 15 минут)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Увеличиваем мощность передатчика на клавиатуре
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y