# --- Bluetooth (1 профиль и максимальная мощность) ---
CONFIG_ZMK_BT=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_BT_MAX_CONN=1
CONFIG_BT_MAX_PAIRED=1

# --- Отключение данных по USB (только зарядка) ---
CONFIG_ZMK_USB=n

# --- Энергосбережение ---
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000