# --- Настройки Bluetooth ---
CONFIG_ZMK_BLE=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# --- Отключаем передачу данных по USB (оставляем только зарядку) ---
CONFIG_ZMK_USB=n

# --- Энергосбережение и сон (крайне важно для чистого BLE) ---
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000