# Включение Bluetooth
CONFIG_ZMK_BLE=y

# Имя клавиатуры при поиске на устройствах
CONFIG_ZMK_KEYBOARD_NAME="My Ortho BLE"

# Повышенная мощность передатчика для стабильной связи (без задержек)
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Включение режима глубокого сна для экономии батарейки
CONFIG_ZMK_SLEEP=y
# Время до ухода в сон — 15 минут (15 * 60 * 1000 мс)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000