# Включение поддержки Bluetooth
CONFIG_ZMK_BLE=y

# Включение ZMK Studio (изменение раскладки на лету)
CONFIG_ZMK_STUDIO=y

# Отключение блокировки студии для мгновенного доступа без пароля
CONFIG_ZMK_STUDIO_LOCKING=n

# Увеличение мощности BLE передатчика для стабильной связи (+8 dBm)
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Глубокий сон для экономии батареи (уходит в сон через 30 минут бездействия)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000