# Включаем режим сплита/периферии (этого достаточно, чтобы ZMK сам понял роль)
CONFIG_ZMK_SPLIT=y

# СТРОКУ НИЖЕ УДАЛИ ИЛИ ЗАКОММЕНТИРУЙ ХЭШТЕНГОМ:
# CONFIG_ZMK_SPLIT_BLE_ROLE_CENTRAL=n  <-- ЭТО ВЫЗЫВАЛО ОШИБКУ СБОРКИ

# Включаем режим сна для экономии батарейки на клавиатуре (15 минут)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Увеличиваем мощность передатчика
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y